name: Build events.csv

on:
  schedule:
    - cron: "0 5 * * *"   # daily at 05:00 UTC
  workflow_dispatch: {}   # allow manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Fetch feeds (ICS only)
        run: python tools/fetch_feeds.py

      - name: Merge manual events
        run: |
          python merge_manual_events.py

      - name: Commit & push if changed
        run: |
          if git diff --quiet; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Update events.csv from feeds + manual"
            git push
          fi
